Name:           ros-lunar-trac-ik-examples
Version:        1.4.10
Release:        0%{?dist}
Summary:        ROS trac_ik_examples package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-lunar-orocos-kdl
Requires:       ros-lunar-pr2-description
Requires:       ros-lunar-trac-ik-lib
Requires:       ros-lunar-xacro
BuildRequires:  boost-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-orocos-kdl
BuildRequires:  ros-lunar-trac-ik-lib

%description
This package contains the source code for testing and comparing trac_ik

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sun Jan 21 2018 Patrick Beeson <pbeeson@traclabs.com> - 1.4.10-0
- Autogenerated by Bloom

* Sat Jan 20 2018 Patrick Beeson <pbeeson@traclabs.com> - 1.4.9-2
- Autogenerated by Bloom

* Sat Jan 20 2018 Patrick Beeson <pbeeson@traclabs.com> - 1.4.9-1
- Autogenerated by Bloom

* Thu Jan 11 2018 Patrick Beeson <pbeeson@traclabs.com> - 1.4.9-0
- Autogenerated by Bloom

* Tue Dec 26 2017 Patrick Beeson <pbeeson@traclabs.com> - 1.4.8-0
- Autogenerated by Bloom

* Tue Dec 26 2017 Patrick Beeson <pbeeson@traclabs.com> - 1.4.7-0
- Autogenerated by Bloom

