%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-trac-ik-lib
Version:        1.6.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS trac_ik_lib package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       NLopt
Requires:       NLopt-devel
Requires:       boost-devel
Requires:       boost-python3-devel
Requires:       ros-noetic-kdl-parser
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-urdf
BuildRequires:  NLopt-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cmake-modules
BuildRequires:  ros-noetic-kdl-parser
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-urdf
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
TRAC-IK is a faster, significantly more reliable drop-in replacement for KDL's
pseudoinverse Jacobian solver. The TRAC-IK library has a very similar API to
KDL's IK solver calls, except that the user passes a maximum time instead of a
maximum number of search iterations. Additionally, TRAC-IK allows for error
tolerances to be set independently for each Cartesian dimension
(x,y,z,roll,pitch.yaw).

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Mar 05 2021 TRACLabs Robotics <robotics@traclabs.com> - 1.6.1-1
- Autogenerated by Bloom

