Name:           ros-melodic-trac-ik
Version:        1.5.0
Release:        1%{?dist}
Summary:        ROS trac_ik package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/trac_ik
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-trac-ik-examples
Requires:       ros-melodic-trac-ik-kinematics-plugin
Requires:       ros-melodic-trac-ik-lib
Requires:       ros-melodic-trac-ik-python
BuildRequires:  ros-melodic-catkin

%description
The ROS packages in this repository were created to provide an improved
alternative Inverse Kinematics solver to the popular inverse Jacobian methods in
KDL. TRAC-IK handles joint-limited chains better than KDL without increasing
solve time.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Aug 22 2018 Patrick Beeson <pbeeson@traclabs.com> - 1.5.0-1
- Autogenerated by Bloom

